spring.application.name=device-registry

server.port=${SERVER_PORT:8080}

management.endpoint.health.show-details=always

spring.config.import=optional:file:.env[.properties]

spring.data.redis.cluster.nodes=${VALKEY_NODES}
spring.data.redis.password=${VALKEY_PASSWORD}

device.registry.server-id=${SERVER_ID}
device.registry.ttl=30s
device.registry.ping=10s

logging.level.dev.yoonsooc.device_registry=DEBUG
