spring.application.name=device-registry

management.endpoint.health.show-details=always

spring.config.import=optional:file:.env[.properties]

spring.data.redis.cluster.nodes=${VALKEY_NODES}
spring.data.redis.password=${VALKEY_PASSWORD}